# generated by datamodel-codegen:
#   filename:  shareloop.openapi.yaml
#   timestamp: 2026-07-05T12:03:18+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import EmailStr, Field
from src.models.base import ApiBaseModel


class Seeding(Enum):
    prompt = 'prompt'
    enabled = 'enabled'


class ServerInfo(ApiBaseModel):
    server_version: str = Field(
        ..., alias='serverVersion', description='Server version (bumped manually)'
    )
    api_version: str = Field(..., alias='apiVersion', description='API version')
    seeding: Seeding | None = Field(
        None,
        description='Seeding status. `null` = disabled (no seed data configured),\n`"prompt"` = seed data available but never seeded,\n`"enabled"` = seeding already performed, available for re-seed.\n',
    )


class Person(ApiBaseModel):
    id: int
    name: str


class Distance(ApiBaseModel):
    km: float


class LatLng(ApiBaseModel):
    lat: float
    lng: float


class RegisterRequest(ApiBaseModel):
    email: EmailStr
    password: str = Field(..., min_length=6)
    name: str = Field(..., min_length=1)


class LoginRequest(ApiBaseModel):
    email: EmailStr
    password: str


class RefreshRequest(ApiBaseModel):
    refresh_token: str = Field(..., alias='refreshToken')


class User(ApiBaseModel):
    id: int
    email: str
    last_online_at: datetime = Field(..., alias='lastOnlineAt')
    created_at: datetime = Field(..., alias='createdAt')


class UserProfile(ApiBaseModel):
    id: int
    name: str
    email: str
    bio: str | None = None
    rating: float | None = None
    created_at: datetime = Field(..., alias='createdAt')
    last_online_at: datetime = Field(..., alias='lastOnlineAt')
    item_count: int = Field(..., alias='itemCount')
    rating_count: int = Field(..., alias='ratingCount')
    share_count: int | None = Field(None, alias='shareCount')


class UserRatingDetail(ApiBaseModel):
    id: int
    reviewer: Person
    friendliness: int = Field(..., ge=1, le=5)
    punctuality: int = Field(..., ge=1, le=5)
    reliability: int = Field(..., ge=1, le=5)
    communication: int | None = Field(None, ge=1, le=5)
    careful_handling: int | None = Field(None, alias='carefulHandling', ge=1, le=5)
    comment: str | None = None
    created_at: datetime = Field(..., alias='createdAt')


class LoginResult(ApiBaseModel):
    user: User
    access_token: str = Field(..., alias='accessToken')
    refresh_token: str = Field(..., alias='refreshToken')
    access_expires_at: datetime = Field(..., alias='accessExpiresAt')
    refresh_expires_at: datetime = Field(..., alias='refreshExpiresAt')


class CreateItemRequest(ApiBaseModel):
    title: str
    description: str
    city: str
    postal_code: str = Field(..., alias='postalCode')
    lat: float
    lng: float
    category: str


class CreateItemResponse(ApiBaseModel):
    id: int


class ItemEditDetail(ApiBaseModel):
    id: int
    title: str
    description: str
    author: Person
    score: float
    city: str | None = None
    postal_code: str | None = Field(None, alias='postalCode')
    image_uuids: list[UUID] = Field(..., alias='imageUuids')
    category: str
    lat: float
    lng: float
    created_at: datetime = Field(..., alias='createdAt')


class UploadItemImageRequest(ApiBaseModel):
    data: str = Field(..., description='Base64-encoded image data')
    filename: str = Field(..., description='Original filename for extension detection')
    sort_order: int = Field(
        ...,
        alias='sortOrder',
        description="Position of this image in the item's image list",
    )


class UploadItemImageResponse(ApiBaseModel):
    uuid: UUID


class UpdateItemRequest(ApiBaseModel):
    title: str
    description: str
    city: str
    postal_code: str = Field(..., alias='postalCode')
    lat: float
    lng: float
    category: str


class SortBy(Enum):
    relevance = 'relevance'
    distance = 'distance'
    score = 'score'
    newest = 'newest'


class ItemSearchRequest(ApiBaseModel):
    query: str | None = None
    lat: float | None = None
    lng: float | None = None
    max_distance_km: float | None = Field(None, alias='maxDistanceKm')
    categories: list[str] | None = None
    min_score: float | None = Field(None, alias='minScore')
    sort_by: SortBy | None = Field(None, alias='sortBy')


class ReorderEntry(ApiBaseModel):
    uuid: UUID
    sort_order: int = Field(..., alias='sortOrder')


class EditItemImagesRequest(ApiBaseModel):
    reorder: list[ReorderEntry]
    delete: list[UUID]


class RentRequestOverview(ApiBaseModel):
    id: int
    item_id: int = Field(..., alias='itemId')
    requester: Person
    item_title: str = Field(..., alias='itemTitle')
    owner_name: str = Field(..., alias='ownerName')
    owner_id: int = Field(..., alias='ownerId')
    latest_accepted_offer_id: int | None = Field(None, alias='latestAcceptedOfferId')
    latest_open_offer_id: int | None = Field(None, alias='latestOpenOfferId')
    borrow_confirmed_at: datetime | None = Field(None, alias='borrowConfirmedAt')
    returned_at: datetime | None = Field(None, alias='returnedAt')
    created_at: datetime = Field(..., alias='createdAt')
    updated_at: datetime = Field(..., alias='updatedAt')
    unread_count: int = Field(..., alias='unreadCount')


class Message(ApiBaseModel):
    id: int
    rent_request_id: int = Field(..., alias='rentRequestId')
    author_id: int = Field(..., alias='authorId')
    content: str
    created_at: datetime = Field(..., alias='createdAt')


class SendMessageRequest(ApiBaseModel):
    content: str


class RentOffer(ApiBaseModel):
    id: int
    rent_request_id: int = Field(..., alias='rentRequestId')
    sender_id: int = Field(..., alias='senderId')
    start_date: datetime = Field(..., alias='startDate')
    end_date: datetime = Field(..., alias='endDate')
    accepted_at: datetime | None = Field(None, alias='acceptedAt')
    created_at: datetime = Field(..., alias='createdAt')
    updated_at: datetime = Field(..., alias='updatedAt')


class UserRating(ApiBaseModel):
    id: int
    rent_request_id: int = Field(..., alias='rentRequestId')
    reviewer_id: int = Field(..., alias='reviewerId')
    reviewee_id: int = Field(..., alias='revieweeId')
    friendliness: int = Field(..., ge=1, le=5)
    punctuality: int = Field(..., ge=1, le=5)
    reliability: int = Field(..., ge=1, le=5)
    communication: int | None = Field(None, ge=1, le=5)
    careful_handling: int | None = Field(None, alias='carefulHandling', ge=1, le=5)
    comment: str | None = None
    created_at: datetime = Field(..., alias='createdAt')


class ItemRating(ApiBaseModel):
    id: int
    rent_request_id: int = Field(..., alias='rentRequestId')
    item_id: int = Field(..., alias='itemId')
    reviewer: Person
    condition: int = Field(..., ge=1, le=5)
    cleanliness: int = Field(..., ge=1, le=5)
    overall: float = Field(..., ge=1.0, le=5.0)
    comment: str | None = None
    created_at: datetime = Field(..., alias='createdAt')


class SubmitUserRatingRequest(ApiBaseModel):
    friendliness: int = Field(..., ge=1, le=5)
    punctuality: int = Field(..., ge=1, le=5)
    reliability: int = Field(..., ge=1, le=5)
    communication: int | None = Field(None, ge=1, le=5)
    careful_handling: int | None = Field(None, alias='carefulHandling', ge=1, le=5)
    comment: str | None = None


class SubmitItemRatingRequest(ApiBaseModel):
    condition: int = Field(..., ge=1, le=5)
    cleanliness: int = Field(..., ge=1, le=5)
    comment: str | None = None


class DateRange(ApiBaseModel):
    start_date: datetime = Field(..., alias='startDate')
    end_date: datetime = Field(..., alias='endDate')


class CreateOfferRequest(ApiBaseModel):
    start_date: datetime = Field(..., alias='startDate')
    end_date: datetime = Field(..., alias='endDate')


class ItemOverview(ApiBaseModel):
    id: int
    title: str
    description: str
    author: Person
    distance: Distance | None = None
    city: str | None = None
    postal_code: str | None = Field(None, alias='postalCode')
    score: float
    image_uuid: str | None = Field(None, alias='imageUuid')
    category: str


class ItemDetail(ApiBaseModel):
    id: int
    title: str
    description: str
    author: Person
    score: float
    city: str | None = None
    postal_code: str | None = Field(None, alias='postalCode')
    image_uuids: list[UUID] = Field(..., alias='imageUuids')
    category: str
    created_at: datetime = Field(..., alias='createdAt')
    item_rating_count: int = Field(..., alias='itemRatingCount', ge=0)
    item_ratings: list[ItemRating] = Field(..., alias='itemRatings')


class RentRequestDetail(ApiBaseModel):
    id: int
    item_id: int = Field(..., alias='itemId')
    requester: Person
    item_title: str = Field(..., alias='itemTitle')
    owner_name: str = Field(..., alias='ownerName')
    owner_id: int = Field(..., alias='ownerId')
    latest_accepted_offer_id: int | None = Field(None, alias='latestAcceptedOfferId')
    latest_open_offer_id: int | None = Field(None, alias='latestOpenOfferId')
    borrow_confirmed_at: datetime | None = Field(None, alias='borrowConfirmedAt')
    returned_at: datetime | None = Field(None, alias='returnedAt')
    created_at: datetime = Field(..., alias='createdAt')
    updated_at: datetime = Field(..., alias='updatedAt')
    messages: list[Message]
    offers: list[RentOffer]
    last_read: datetime = Field(..., alias='lastRead')
    my_user_rating: UserRating | None = Field(None, alias='myUserRating')
    my_item_rating: ItemRating | None = Field(None, alias='myItemRating')
