"""add avatar uuid to profiles

Revision ID: 91b3e29fa96f
Revises: d9a73830900c
Create Date: 2026-06-30 15:34:31.609841
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '91b3e29fa96f'
down_revision: Union[str, None] = 'd9a73830900c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_uuid', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'avatar_uuid')
    # ### end Alembic commands ###
