"""make price_per_day not null

Revision ID: 933850ea0c37
Revises: 0369874035aa
Create Date: 2026-07-05 12:10:54.895411
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '933850ea0c37'
down_revision: Union[str, None] = '0369874035aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE items SET price_per_day = 0 WHERE price_per_day IS NULL")
    op.alter_column('items', 'price_per_day',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price_per_day',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
