// Code generated by oaspec v0.68.0. DO NOT EDIT.

import openapi/types

pub type LoginResponse {
  LoginResponseOk(types.LoginResult)
  LoginResponseUnauthorized
  LoginResponseInternalServerError
}

pub type LogoutResponse {
  LogoutResponseNoContent
  LogoutResponseUnauthorized
  LogoutResponseInternalServerError
}

pub type RefreshResponse {
  RefreshResponseOk(types.LoginResult)
  RefreshResponseUnauthorized
  RefreshResponseInternalServerError
}

pub type VerifyResponse {
  VerifyResponseOk(types.User)
  VerifyResponseUnauthorized
  VerifyResponseInternalServerError
}

pub type GetFeaturedItemsResponse {
  GetFeaturedItemsResponseOk(List(types.ItemOverview))
  GetFeaturedItemsResponseInternalServerError
}

pub type GetImageResponse {
  GetImageResponseOk(String)
  GetImageResponseNotFound
  GetImageResponseInternalServerError
}

pub type CreateItemResponse {
  CreateItemResponseCreated(types.CreateItemResponse)
  CreateItemResponseUnauthorized
  CreateItemResponseInternalServerError
}

pub type SearchItemsResponse {
  SearchItemsResponseOk(List(types.ItemOverview))
  SearchItemsResponseInternalServerError
}

pub type GetItemResponse {
  GetItemResponseOk(types.ItemDetail)
  GetItemResponseNotFound
  GetItemResponseInternalServerError
}

pub type UpdateItemResponse {
  UpdateItemResponseOk(types.CreateItemResponse)
  UpdateItemResponseUnauthorized
  UpdateItemResponseForbidden
  UpdateItemResponseNotFound
  UpdateItemResponseInternalServerError
}

pub type GetItemEditResponse {
  GetItemEditResponseOk(types.ItemEditDetail)
  GetItemEditResponseUnauthorized
  GetItemEditResponseForbidden
  GetItemEditResponseNotFound
  GetItemEditResponseInternalServerError
}

pub type UploadItemImageResponse {
  UploadItemImageResponseCreated(types.UploadItemImageResponse)
  UploadItemImageResponseUnauthorized
  UploadItemImageResponseForbidden
  UploadItemImageResponseNotFound
  UploadItemImageResponseInternalServerError
}

pub type EditItemImagesResponse {
  EditItemImagesResponseNoContent
  EditItemImagesResponseUnauthorized
  EditItemImagesResponseForbidden
  EditItemImagesResponseNotFound
  EditItemImagesResponseInternalServerError
}

pub type CreateRentRequestResponse {
  CreateRentRequestResponseCreated(types.RentRequestDetail)
  CreateRentRequestResponseUnauthorized
  CreateRentRequestResponseInternalServerError
}

pub type AcceptOfferResponse {
  AcceptOfferResponseOk(types.RentOffer)
  AcceptOfferResponseUnauthorized
  AcceptOfferResponseForbidden
  AcceptOfferResponseNotFound
  AcceptOfferResponseInternalServerError
}

pub type GetRentRequestsResponse {
  GetRentRequestsResponseOk(List(types.RentRequestOverview))
  GetRentRequestsResponseUnauthorized
  GetRentRequestsResponseInternalServerError
}

pub type GetRentRequestResponse {
  GetRentRequestResponseOk(types.RentRequestDetail)
  GetRentRequestResponseUnauthorized
  GetRentRequestResponseNotFound
  GetRentRequestResponseInternalServerError
}

pub type ConfirmBorrowResponse {
  ConfirmBorrowResponseOk(types.RentRequestDetail)
  ConfirmBorrowResponseUnauthorized
  ConfirmBorrowResponseForbidden
  ConfirmBorrowResponseNotFound
  ConfirmBorrowResponseInternalServerError
}

pub type ConfirmReturnResponse {
  ConfirmReturnResponseOk(types.RentRequestDetail)
  ConfirmReturnResponseUnauthorized
  ConfirmReturnResponseForbidden
  ConfirmReturnResponseNotFound
  ConfirmReturnResponseInternalServerError
}

pub type MarkRentRequestReadResponse {
  MarkRentRequestReadResponseNoContent
  MarkRentRequestReadResponseUnauthorized
  MarkRentRequestReadResponseNotFound
  MarkRentRequestReadResponseInternalServerError
}

pub type SendMessageResponse {
  SendMessageResponseCreated(types.Message)
  SendMessageResponseUnauthorized
  SendMessageResponseNotFound
  SendMessageResponseInternalServerError
}

pub type CreateOfferResponse {
  CreateOfferResponseCreated(types.RentOffer)
  CreateOfferResponseUnauthorized
  CreateOfferResponseNotFound
  CreateOfferResponseInternalServerError
}
